### ISSUE TITLE
I Know Another Fix!

### ISSUE THREAD

**Issue by Topher7lol** [CommanderGL/UBTW2#1]
If running in Cloud Shell (Google), run `#!/bin/bash ./install.sh Velocity` or `#!/bin/bash ./install.sh nodeunblocker.com`

And for running you'd type

`#!/bin/bash ./launch.sh Velocity` or `#!/bin/bash ./launch.sh nodeunblocker.com`

For me, nodeunblocker.com is blocked on my school website so I use Velocity, and it actually works! Thanks bro

**Comment by CommanderGL** [comment]
Are you sure you need the `#!/bin/bash` part as I am already using `#!/bin/env bash` which should be equivalent.

**Comment by CommanderGL** [comment]
Also if this isn't an issue please close it.
